"""Executable mathematical algorithm generated by Algorithmic Genesis.
Name: ag_chaotic_map_explorer_dc0f1a3431df
Kind: chaotic_map_explorer
Domain: chaotic_maps
This file is deterministic, gas-limited and numeric-poison-contained.
"""
from __future__ import annotations
import math
from typing import Callable, Iterable

DEFAULT_GAS = 10000

def sanitize(v: float) -> float:
    try:
        x = float(v)
    except Exception:
        return 0.0
    if not math.isfinite(x):
        return 0.0
    return max(-1_000_000.0, min(1_000_000.0, x))

def expclamp(x: float) -> float:
    return math.exp(max(-20.0, min(20.0, sanitize(x))))

def logabs(x: float) -> float:
    return math.log(abs(sanitize(x)) + 1e-9)

def kernel(x: float, gas_left: int = DEFAULT_GAS) -> float:
    if gas_left <= 0:
        return 0.0
    x = sanitize(x)
    try:
        return sanitize(math.tanh(math.tanh(((x * math.cos(x)) / (x * math.cos(x))))))
    except Exception:
        return 0.0

def transform_scalar(x: float, gas_left: int = DEFAULT_GAS) -> tuple[float, int]:
    if gas_left <= 0:
        return 0.0, 1
    return kernel(x, gas_left - 1), 0

def fixed_point(x0: float, iterations: int = 128, tol: float = 1e-9, gas_left: int = DEFAULT_GAS) -> tuple[float, int]:
    x = sanitize(x0)
    for _ in range(max(0, iterations)):
        gas_left -= 1
        if gas_left <= 0:
            return x, 1
        y = sanitize(0.65 * x + 0.35 * math.tanh(kernel(x, gas_left)))
        if abs(y - x) <= tol:
            return y, 0
        x = y
    return x, 0

def signal_morph(signal: Iterable[float], gas_left: int = DEFAULT_GAS) -> tuple[list[float], int]:
    out: list[float] = []
    state = 0.0
    for s in signal:
        gas_left -= 1
        if gas_left <= 0:
            return out, 1
        x = sanitize(float(s) + 0.25 * state)
        y = sanitize(0.70 * float(s) + 0.30 * math.tanh(kernel(x, gas_left)))
        state = sanitize(0.8 * state + 0.2 * y)
        out.append(y)
    return out, 0

def predict_next(values: list[float], gas_left: int = DEFAULT_GAS) -> tuple[float, int]:
    if len(values) < 2 or gas_left <= 0:
        return 0.0, 1
    a, b = sanitize(values[-2]), sanitize(values[-1])
    d = sanitize(b - a)
    return sanitize(b + d + 0.1 * math.tanh(kernel(d, gas_left - 1))), 0

def explore_map(x0: float, iterations: int = 256, gas_left: int = DEFAULT_GAS) -> tuple[dict, int]:
    x = sanitize(x0)
    orbit = []
    lyap = 0.0
    eps = 1e-5
    for _ in range(max(0, iterations)):
        gas_left -= 2
        if gas_left <= 0:
            return {'orbit': orbit, 'lyapunov_like': lyap / max(1, len(orbit))}, 1
        x1 = sanitize(math.tanh(kernel(x, gas_left)))
        xp = sanitize(math.tanh(kernel(x + eps, gas_left)))
        lyap += math.log(abs((xp - x1) / eps) + 1e-9)
        x = x1
        orbit.append(x)
    return {'orbit': orbit, 'lyapunov_like': lyap / max(1, len(orbit))}, 0

ROOT_FEATURES = (
    'x','fx','lo','hi','flo','fhi','mid','width','relpos',
    'prev_x','prev_fx','prev2_x','prev2_fx',
    'bracket_slope','local_slope','prev_slope','curvature',
    'improvement','stagnation','trust','reject_rate',
    'scale','nfx','nflo','nfhi','nwidth','sign_change',
    'edge_balance','residual_ratio','width_ratio'
)

def _safe_div(a: float, b: float) -> float:
    b = sanitize(b)
    if abs(b) <= 1e-12:
        return 0.0
    return sanitize(a / b)

def make_root_context(x: float, fx: float, lo: float, hi: float, flo: float, fhi: float,
                      prev_x: float, prev_fx: float, prev2_x: float, prev2_fx: float,
                      prev_best: float, best_r: float, stagnation: float, trust: float,
                      reject_rate: float, initial_width: float) -> dict[str, float]:
    lo = sanitize(lo); hi = sanitize(hi); x = sanitize(x); fx = sanitize(fx)
    flo = sanitize(flo); fhi = sanitize(fhi)
    width = abs(hi - lo) + 1e-12
    mid = sanitize(0.5 * (lo + hi))
    relpos = max(0.0, min(1.0, (x - lo) / width))
    bracket_slope = _safe_div(fhi - flo, width)
    local_slope = _safe_div(fx - prev_fx, x - prev_x)
    prev_slope = _safe_div(prev_fx - prev2_fx, prev_x - prev2_x)
    curvature = sanitize(local_slope - prev_slope)
    improvement = sanitize(prev_best - best_r)
    scale = abs(flo) + abs(fhi) + abs(fx) + 1e-9
    nfx = sanitize(fx / scale)
    nflo = sanitize(flo / scale)
    nfhi = sanitize(fhi / scale)
    nwidth = sanitize(math.log1p(width))
    sign_change = -1.0 if flo * fhi <= 0.0 else 1.0
    edge_balance = sanitize((abs(flo) - abs(fhi)) / (abs(flo) + abs(fhi) + 1e-9))
    residual_ratio = sanitize(abs(fx) / (min(abs(flo), abs(fhi)) + 1e-9))
    width_ratio = sanitize(width / (abs(initial_width) + 1e-12))
    return {
        'x': x, 'fx': fx, 'lo': lo, 'hi': hi, 'flo': flo, 'fhi': fhi,
        'mid': mid, 'width': width, 'relpos': relpos,
        'prev_x': sanitize(prev_x), 'prev_fx': sanitize(prev_fx),
        'prev2_x': sanitize(prev2_x), 'prev2_fx': sanitize(prev2_fx),
        'bracket_slope': bracket_slope, 'local_slope': local_slope,
        'prev_slope': prev_slope, 'curvature': curvature,
        'improvement': improvement, 'stagnation': sanitize(stagnation),
        'trust': max(0.0, min(1.0, sanitize(trust))),
        'reject_rate': max(0.0, min(1.0, sanitize(reject_rate))),
        'scale': scale, 'nfx': nfx, 'nflo': nflo, 'nfhi': nfhi,
        'nwidth': nwidth, 'sign_change': sign_change,
        'edge_balance': edge_balance, 'residual_ratio': residual_ratio,
        'width_ratio': width_ratio,
    }

def context_kernel(x: float, fx: float, flo: float, fhi: float, history: float, width: float, gas_left: int = DEFAULT_GAS) -> float:
    # Backward-compatible scalar contextual primitive.
    if gas_left <= 0:
        return 0.0
    x = sanitize(x); fx = sanitize(fx); flo = sanitize(flo); fhi = sanitize(fhi)
    history = sanitize(history); width = abs(sanitize(width)) + 1e-12
    kx = kernel(x, gas_left - 1)
    kfx = kernel(0.25 * fx, gas_left - 1)
    kedge = kernel(0.5 * (flo + fhi), gas_left - 1)
    slope_hint = sanitize((fhi - flo) / width)
    residual_pressure = sanitize(math.tanh(fx) - 0.5 * math.tanh(flo + fhi))
    return sanitize(0.42 * kx + 0.22 * kfx - 0.16 * kedge + 0.12 * history + 0.08 * math.tanh(slope_hint) + residual_pressure)

def root_policy(ctx: dict[str, float], gas_left: int = DEFAULT_GAS) -> dict[str, float]:
    # High-dimensional generated root policy.
    # The discovered scalar kernel is evaluated on many normalized context projections.
    # Outputs are bounded controls for a safe candidate mixer, not direct roots.
    if gas_left <= 0:
        return {'bias': 0.0, 'damping': 0.0, 'secant_mix': 0.0, 'bisection_mix': 1.0, 'relaxation_mix': 0.0, 'trust_delta': -0.1}
    kx = kernel(ctx['x'], gas_left - 1)
    kres = kernel(ctx['nfx'] + 0.25 * ctx['edge_balance'], gas_left - 1)
    kslope = kernel(math.tanh(ctx['bracket_slope']) + 0.5 * math.tanh(ctx['local_slope']), gas_left - 1)
    kcurve = kernel(math.tanh(ctx['curvature']) - 0.2 * ctx['stagnation'], gas_left - 1)
    ktrust = kernel(ctx['trust'] - ctx['reject_rate'] + ctx['improvement'], gas_left - 1)
    instability = max(0.0, min(1.0, abs(math.tanh(ctx['curvature'])) + ctx['reject_rate'] + 0.25 * ctx['stagnation']))
    bias = math.tanh(0.30 * kx + 0.30 * kres + 0.20 * kslope - 0.10 * kcurve + 0.10 * ktrust)
    damping = max(0.02, min(1.0, 0.65 + 0.25 * math.tanh(ktrust) - 0.45 * instability))
    secant_mix = max(0.0, min(1.0, 0.35 + 0.25 * math.tanh(kslope) + 0.20 * ctx['trust'] - 0.35 * instability))
    relaxation_mix = max(0.0, min(1.0, 0.30 + 0.25 * math.tanh(kres + kcurve) + 0.20 * ctx['trust'] - 0.25 * ctx['reject_rate']))
    bisection_mix = max(0.10, min(1.0, 1.0 - 0.5 * secant_mix - 0.4 * relaxation_mix + 0.45 * instability))
    trust_delta = sanitize(0.05 * math.tanh(ktrust + ctx['improvement']) - 0.08 * ctx['reject_rate'] - 0.03 * ctx['stagnation'])
    return {
        'bias': sanitize(bias), 'damping': sanitize(damping),
        'secant_mix': sanitize(secant_mix), 'bisection_mix': sanitize(bisection_mix),
        'relaxation_mix': sanitize(relaxation_mix), 'trust_delta': trust_delta,
    }

def _candidate_mixer(ctx: dict[str, float], policy: dict[str, float]) -> float:
    lo, hi, width, mid = ctx['lo'], ctx['hi'], ctx['width'], ctx['mid']
    secant = mid
    if abs(ctx['bracket_slope']) > 1e-12:
        secant = ctx['x'] - ctx['fx'] / ctx['bracket_slope']
    learned = mid - 0.5 * width * policy['damping'] * math.tanh(policy['bias'])
    wb = policy['bisection_mix']; ws = policy['secant_mix']; wr = policy['relaxation_mix']
    z = wb + ws + wr + 1e-12
    cand = (wb * mid + ws * secant + wr * learned) / z
    return min(max(sanitize(cand), lo), hi)

def root_refine(f: Callable[[float], float], lo: float, hi: float, iterations: int = 128, gas_left: int = DEFAULT_GAS) -> tuple[float, int]:
    lo, hi = sanitize(lo), sanitize(hi)
    if lo == hi:
        return lo, 2
    if lo > hi:
        lo, hi = hi, lo
    initial_width = abs(hi - lo) + 1e-12
    flo, fhi = sanitize(f(lo)), sanitize(f(hi))
    if flo == 0.0:
        return lo, 0
    if fhi == 0.0:
        return hi, 0
    if flo * fhi > 0.0:
        return sanitize(0.5 * (lo + hi)), 3
    best_x, best_r = (lo, abs(flo)) if abs(flo) <= abs(fhi) else (hi, abs(fhi))
    prev_x = prev2_x = 0.5 * (lo + hi)
    prev_fx = prev2_fx = sanitize(f(prev_x))
    trust = 0.35
    reject_rate = 0.0
    stagnation = 0.0
    for _ in range(max(0, iterations)):
        gas_left -= 8
        if gas_left <= 0:
            return best_x, 1
        mid = sanitize(0.5 * (lo + hi))
        fm = sanitize(f(mid))
        old_best = best_r
        ctx = make_root_context(mid, fm, lo, hi, flo, fhi, prev_x, prev_fx, prev2_x, prev2_fx, old_best, best_r, stagnation, trust, reject_rate, initial_width)
        policy = root_policy(ctx, gas_left)
        cand = _candidate_mixer(ctx, policy)
        if abs(cand - lo) < 1e-15 or abs(cand - hi) < 1e-15 or not math.isfinite(cand):
            cand = mid
        fc = sanitize(f(cand))
        rejected = False
        if abs(fm) < abs(fc) or not math.isfinite(fc):
            cand, fc = mid, fm
            rejected = True
        if abs(fc) < best_r:
            best_x, best_r = cand, abs(fc)
        improvement = old_best - best_r
        stagnation = 0.0 if improvement > max(1e-14, 1e-6 * old_best) else min(64.0, stagnation + 1.0)
        reject_rate = sanitize(0.90 * reject_rate + 0.10 * (1.0 if rejected else 0.0))
        trust = max(0.0, min(1.0, trust + policy['trust_delta'] + (0.025 if improvement > 0 else -0.015)))
        prev2_x, prev2_fx = prev_x, prev_fx
        prev_x, prev_fx = cand, fc
        if fc == 0.0 or abs(hi - lo) <= 1e-12:
            return cand, 0
        if (flo < 0 and fc > 0) or (flo > 0 and fc < 0):
            hi, fhi = cand, fc
        else:
            lo, flo = cand, fc
    return best_x, 0

def run_demo() -> None:
    print('algorithm:', 'ag_chaotic_map_explorer_dc0f1a3431df')
    print('kernel(0.5)=', kernel(0.5))
    print('fixed_point=', fixed_point(0.25)[0])
    print('predict_next=', predict_next([0.0, 0.5, 0.75])[0])

if __name__ == '__main__':
    run_demo()
